name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

    steps:
      - name: Clone Project
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - name: Create Changelog Content
        id: changelog
        uses: loopwerk/tag-changelog@v1.3.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            config_file: .github/actions-changelog-config.js   
            
      - name: Update Release
        uses: mini-bomba/create-github-release@v1.2.0
        with:
          skip_tag_creation: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          body: ${{ steps.changelog.outputs.changes }}
          
      - name: Create Latest Changelog    
        run: echo "${{ steps.changelog.outputs.changes }}" >> CHANGELOG.md

      - name: Pack it up and upload it
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1363592 -n "{package-name}-{project-version}"
